/******************************************************************************
*  Generated by PSoC Designer 5.0.423.0
******************************************************************************/
#include "DigBuf_1.h"
#include "DigBuf_2.h"
#include "E2PROM_1.h"
#include "I2CHW_1Mstr.h"
#include "I2CHW_1Common.h"
#include "PWM16_1.h"
#include "PWM16_2.h"
#include "Timer8_1.h"
#include "UART.h"
#include "UART_MIRR.h"
